static inline int CPU6_inst_unknown(CPU6_machine_t *m, byte_t op);
static inline int CPU6_fetch_byte(CPU6_machine_t *m);
static inline int CPU6_fetch_word(CPU6_machine_t *m);
static inline int CPU6_fetch_op(CPU6_machine_t *m);
static inline int CPU6_halt(CPU6_machine_t *m);
static inline int CPU6_nop(CPU6_machine_t *m);
static inline int CPU6_delay(CPU6_machine_t *m);
static inline int CPU6_set_flags(CPU6_machine_t *m, enum CPU6_FLAGS f);
static inline int CPU6_clear_flags(CPU6_machine_t *m, enum CPU6_FLAGS f);
static inline int CPU6_toggle_flags(CPU6_machine_t *m, enum CPU6_FLAGS f);
static inline int CPU6_check_flags_set(CPU6_machine_t *m, enum CPU6_FLAGS f);
static inline int CPU6_check_flags_clear(CPU6_machine_t *m, enum CPU6_FLAGS f);
static inline int CPU6_check_sense_switch_set(CPU6_machine_t *m, byte_t sw);
static inline int CPU6_check_tty_state(CPU6_machine_t *m, char st);
static inline int CPU6_check_parity_state(CPU6_machine_t *m, char st);
static inline int CPU6_tty_enable_link_out(CPU6_machine_t *m);
static inline int CPU6_get_reg8(CPU6_machine_t *m, nibble_t reg);
static inline int CPU6_get_reg16(CPU6_machine_t *m, nibble_t reg);
static inline int CPU6_set_reg8(CPU6_machine_t *m, nibble_t reg, byte_t val);
static inline int CPU6_set_reg16(CPU6_machine_t *m, nibble_t reg, word_t val);
static inline int CPU6_reg_push_byte(CPU6_machine_t *m, nibble_t reg, byte_t val);
static inline int CPU6_reg_push_word(CPU6_machine_t *m, nibble_t reg, word_t val);
static inline int CPU6_reg_pop_byte(CPU6_machine_t *m, nibble_t reg);
static inline int CPU6_reg_pop_word(CPU6_machine_t *m, nibble_t reg);
static inline int CPU6_stack_push_byte(CPU6_machine_t *m, byte_t val);
static inline int CPU6_stack_push_word(CPU6_machine_t *m, word_t val);
static inline int CPU6_stack_pop_byte(CPU6_machine_t *m);
static inline int CPU6_stack_pop_word(CPU6_machine_t *m);
static inline int CPU6_stack_push_reg8(CPU6_machine_t *m, nibble_t reg);
static inline int CPU6_stack_push_reg16(CPU6_machine_t *m, nibble_t reg);
static inline int CPU6_stack_pop_reg8(CPU6_machine_t *m, nibble_t reg);
static inline int CPU6_stack_pop_reg16(CPU6_machine_t *m, nibble_t reg);
static inline int CPU6_stack_push_reg_range(CPU6_machine_t *m);
static inline int CPU6_stack_pop_reg_range(CPU6_machine_t *m);
static inline int CPU6_set_IE(CPU6_machine_t *m);
static inline int CPU6_clear_IE(CPU6_machine_t *m);
static inline int CPU6_get_IE(CPU6_machine_t *m);
static inline int CPU6_get_LV(CPU6_machine_t *m);
static inline int CPU6_set_LV(CPU6_machine_t *m, byte_t lv);
static inline int CPU6_return_int(CPU6_machine_t *m, char mode);
static inline int CPU6_get_PC(CPU6_machine_t *m);
static inline int CPU6_set_PC(CPU6_machine_t *m, word_t addr);
static inline int CPU6_inc_PC(CPU6_machine_t *m);
static inline int CPU6_xfr_PC_X(CPU6_machine_t *m);
static inline int CPU6_cond_branch(CPU6_machine_t *m, bit_t cond);
static inline int CPU6_MEM_JMP_decode(CPU6_machine_t *m, byte_t amode);
static inline int CPU6_MEM_JSR_decode(CPU6_machine_t *m, byte_t amode);
static inline int CPU6_return_sub(CPU6_machine_t *m);
static inline int CPU6_MEM_read_byte(CPU6_machine_t *m, word_t addr);
static inline int CPU6_MEM_read_word(CPU6_machine_t *m, word_t addr);
static inline int CPU6_MEM_write_byte(CPU6_machine_t *m, word_t addr, byte_t val);
static inline int CPU6_MEM_write_word(CPU6_machine_t *m, word_t addr, word_t val);
static inline int CPU6_get_MAP(CPU6_machine_t *m);
static inline int CPU6_set_MAP(CPU6_machine_t *m, octal_t map);
static inline int CPU6_MEM_MAP_translate(CPU6_machine_t *m, word_t addr);
static inline int CPU6_MEM_MAP_read_byte(CPU6_machine_t *m, word_t addr);
static inline int CPU6_MEM_MAP_write_byte(CPU6_machine_t *m, word_t addr, byte_t val);
static inline int CPU6_MEM_LD_decode(CPU6_machine_t *m, bit_t opw, byte_t amode, nibble_t reg);
static inline int CPU6_MEM_ST_decode(CPU6_machine_t *m, bit_t opw, byte_t amode, nibble_t reg);
static inline int CPU6_fetch_byte_amode_mem(CPU6_machine_t *m, byte_t amode);
static inline int CPU6_fetch_word_amode_mem(CPU6_machine_t *m, byte_t amode);
static inline int CPU6_fetch_addr_amode_mem(CPU6_machine_t *m, byte_t amode);
static inline int CPU6_fetch_addr_amode_idx(CPU6_machine_t *m);
static inline int CPU6_ALU_op1r(CPU6_machine_t *m, bit_t opw, byte_t op, int reg);
static inline int CPU6_ALU_op2r(CPU6_machine_t *m, bit_t opw, byte_t op, int sr, int dr);
